### ISSUE TITLE
Question regarding query timeout implementation

### ISSUE THREAD

**Issue by lbruand-poctu** [hmsonline/storm-cassandra-cql#31]
Hi!

Thanks for your driver. It is great.

https://github.com/hmsonline/storm-cassandra-cql/blame/master/src/main/java/com/hmsonline/trident/cql/CassandraCqlStateFactory.java#L21

Query timeout configuration does not seem to be implemented.
When do you plan to implement it ?
Do you need help ?

Cheers,
Lucas

**Comment by boneill42** [comment]
Your right.  We plan to implement it, but I'm not sure when we'll get around to it.
If you would like to take a stab at it, we love pull requests. =)

**Comment by lrenn** [comment]
This is coming in 0.3.0.  You'll be able to configure pretty much anything you can configure with a [Cluster.Builder](http://www.datastax.com/drivers/java/2.0/com/datastax/driver/core/Cluster.Builder.html) or pass your own Cluster instance into CqlClientFactory.

**Comment by boneill42** [comment]
Now merged into master.  Have a look at:
https://github.com/hmsonline/storm-cassandra-cql/blob/master/src/test/java/com/hmsonline/trident/cql/MapConfiguredCqlClientFactoryTest.java

Updated documentation (README) to reference this as well.

@lbruand-poctu let us know if this doesn't meet your needs, or if you have suggestions on a better way to expose it.

This will be available in 0.3.0, closing issue.
