### ISSUE TITLE
is CassandraCqlState leaking statments?

### ISSUE THREAD

**Issue by lbruand-poctu** [hmsonline/storm-cassandra-cql#37]
Hello,

We are seeing degradation on performance with time.
So we are believing we have a leak somewhere.
 Should not we have some sort of reset of the ```this.statements``` field in the end of the ```commit``` method :

https://github.com/hmsonline/storm-cassandra-cql/blob/master/src/main/java/com/hmsonline/trident/cql/CassandraCqlState.java#L56

```java
this.statements.clear();
```

**Comment by lbruand-poctu** [comment]
After some tests, the leak is solved!

**Comment by boneill42** [comment]
Great to hear Lucas, and fantastic catch.
Thanks for the feedback.

**Comment by leerobert** [comment]
Nice catch!

**Comment by lbruand-poctu** [comment]
Thx !
